/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import static java.awt.Frame.MAXIMIZED_BOTH;
import utilitario.EscritorioVendedor;

/**
 *
 * @author thiag
 */
public class frmVendedorPrincipal extends javax.swing.JFrame {
    private EscritorioVendedor escritorio;

    /**
     * Creates new form frmVendedorPrincipal
     */
    public frmVendedorPrincipal() {
        initComponents();
        escritorio = new EscritorioVendedor();
        this.setContentPane(escritorio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        mnBarra = new javax.swing.JMenuBar();
        mnClientes = new javax.swing.JMenu();
        mnitmListaClientes = new javax.swing.JMenuItem();
        mnCotizacion = new javax.swing.JMenu();
        mnPagos = new javax.swing.JMenu();
        mnVentas = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        mnClientes.setText("Clientes");

        mnitmListaClientes.setText("Lista de clientes");
        mnitmListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmListaClientesActionPerformed(evt);
            }
        });
        mnClientes.add(mnitmListaClientes);

        mnBarra.add(mnClientes);

        mnCotizacion.setText("Cotización");
        mnBarra.add(mnCotizacion);

        mnPagos.setText("Pagos");
        mnBarra.add(mnPagos);

        mnVentas.setText("Ventas");
        mnBarra.add(mnVentas);

        mnSalir.setText("Salir");
        mnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSalirMouseClicked(evt);
            }
        });
        mnBarra.add(mnSalir);

        setJMenuBar(mnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0); 
    }//GEN-LAST:event_mnSalirMouseClicked

    private void mnitmListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmListaClientesActionPerformed
        // TODO add your handling code here:
        frmVendedorCliente frm = new frmVendedorCliente();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_mnitmListaClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVendedorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVendedorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVendedorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVendedorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmVendedorPrincipal frm = new frmVendedorPrincipal();
                frm.setExtendedState(MAXIMIZED_BOTH);
                frm.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar mnBarra;
    private javax.swing.JMenu mnClientes;
    private javax.swing.JMenu mnCotizacion;
    private javax.swing.JMenu mnPagos;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JMenu mnVentas;
    private javax.swing.JMenuItem mnitmListaClientes;
    // End of variables declaration//GEN-END:variables
}
